### ISSUE TITLE
UnscopedSQL exceptions for SET statement when running rake db:fixtures:load

### ISSUE THREAD

**Issue by stewi2** [zendesk/arsi#12]
I was trying to update the classic fixtures in my Docker DB, and it's triggering a warning about unscoped SQL where it obviously is irrelevant (because they're just updating settings in MySQL).
- Perhaps the check should only apply to DML statements ?
- Or am I doing this wrong, and I should be running some other command to re-load the fixtures ? Since this is Rails code, I don't think I can use without_arsi, as the output suggests.
- Or is this just a warning that can be ignored ?

```
stefans-macbook-air:~ stefan$ zdi zendesk -d run bundle exec rake db:fixtures:load
I, [2015-06-07T14:24:02.856969 #95803]  INFO -- : all gems in container
rake aborted!
Arsi::UnscopedSQL: Missing ID in the where sql:
SET FOREIGN_KEY_CHECKS = 1
Add id or use without_arsi
/app/vendor/cache/arsi-17e440fc82b5/lib/arsi.rb:22:in `block in <module:Arsi>'
/app/vendor/cache/arsi-17e440fc82b5/lib/arsi.rb:65:in `call'
/app/vendor/cache/arsi-17e440fc82b5/lib/arsi.rb:65:in `report_violation'
/app/vendor/cache/arsi-17e440fc82b5/lib/arsi.rb:31:in `sql_check!'
/app/vendor/cache/arsi-17e440fc82b5/lib/arsi.rb:36:in `arel_check!'
/app/vendor/cache/arsi-17e440fc82b5/lib/arsi/mysql2_adapter.rb:11:in `update'
Arsi::UnscopedSQL: Missing ID in the where sql:
SET FOREIGN_KEY_CHECKS = 0
Add id or use without_arsi
/app/vendor/cache/arsi-17e440fc82b5/lib/arsi.rb:22:in `block in <module:Arsi>'
/app/vendor/cache/arsi-17e440fc82b5/lib/arsi.rb:65:in `call'
/app/vendor/cache/arsi-17e440fc82b5/lib/arsi.rb:65:in `report_violation'
/app/vendor/cache/arsi-17e440fc82b5/lib/arsi.rb:31:in `sql_check!'
/app/vendor/cache/arsi-17e440fc82b5/lib/arsi.rb:36:in `arel_check!'
/app/vendor/cache/arsi-17e440fc82b5/lib/arsi/mysql2_adapter.rb:11:in `update'
Tasks: TOP => db:fixtures:load
(See full trace by running task with --trace)
```

**Comment by zenspider** [comment]
8 years later... I don't think this is an issue. Closing.
